<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="{{ $name }}-menu">
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">UTC</li>

	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/New_York</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Chicago</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Denver</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Los_Angeles</li>

	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Warsaw</li>

	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Hong_Kong</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Seoul</li>

	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">frica/Abidjan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Accra</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Addis_Ababa</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Algiers</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Asmara</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Bamako</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Bangui</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Banjul</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Bissau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Blantyre</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Brazzaville</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Bujumbura</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Cairo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Casablanca</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Ceuta</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Conakry</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Dakar</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Dar_es_Salaam</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Djibouti</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Douala</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/El_Aaiun</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Freetown</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Gaborone</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Harare</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Johannesburg</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Juba</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Kampala</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Khartoum</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Kigali</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Kinshasa</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Lagos</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Libreville</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Lome</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Luanda</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Lubumbashi</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Lusaka</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Malabo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Maputo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Maseru</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Mbabane</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Mogadishu</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Monrovia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Nairobi</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Ndjamena</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Niamey</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Nouakchott</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Ouagadougou</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Porto-Novo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Sao_Tome</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Tripoli</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Tunis</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Africa/Windhoek</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Adak</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Anchorage</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Anguilla</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Antigua</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Araguaina</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Buenos_Aires</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Catamarca</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Cordoba</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Jujuy</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/La_Rioja</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Mendoza</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Rio_Gallegos</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Salta</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/San_Juan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/San_Luis</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Tucuman</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Argentina/Ushuaia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Aruba</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Asuncion</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Atikokan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Bahia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Bahia_Banderas</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Barbados</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Belem</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Belize</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Blanc-Sablon</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Boa_Vista</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Bogota</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Boise</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Cambridge_Bay</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Campo_Grande</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Cancun</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Caracas</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Cayenne</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Cayman</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Chihuahua</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Costa_Rica</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Creston</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Cuiaba</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Curacao</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Danmarkshavn</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Dawson</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Dawson_Creek</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Detroit</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Dominica</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Edmonton</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Eirunepe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/El_Salvador</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Fort_Nelson</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Fortaleza</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Glace_Bay</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Godthab</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Goose_Bay</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Grand_Turk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Grenada</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Guadeloupe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Guatemala</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Guayaquil</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Guyana</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Halifax</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Havana</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Hermosillo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Indianapolis</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Knox</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Marengo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Petersburg</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Tell_City</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Vevay</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Vincennes</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Indiana/Winamac</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Inuvik</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Iqaluit</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Jamaica</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Juneau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Kentucky/Louisville</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Kentucky/Monticello</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Kralendijk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/La_Paz</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Lima</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Lower_Princes</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Maceio</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Managua</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Manaus</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Marigot</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Martinique</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Matamoros</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Mazatlan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Menominee</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Merida</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Metlakatla</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Mexico_City</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Miquelon</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Moncton</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Monterrey</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Montevideo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Montserrat</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Nassau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Nipigon</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Nome</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Noronha</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/North_Dakota/Beulah</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/North_Dakota/Center</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/North_Dakota/New_Salem</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Ojinaga</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Panama</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Pangnirtung</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Paramaribo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Phoenix</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Port-au-Prince</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Port_of_Spain</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Porto_Velho</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Puerto_Rico</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Rainy_River</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Rankin_Inlet</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Recife</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Regina</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Resolute</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Rio_Branco</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Santarem</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Santiago</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Santo_Domingo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Sao_Paulo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Scoresbysund</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Sitka</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/St_Barthelemy</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/St_Johns</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/St_Kitts</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/St_Lucia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/St_Thomas</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/St_Vincent</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Swift_Current</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Tegucigalpa</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Thule</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Thunder_Bay</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Tijuana</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Toronto</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Tortola</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Vancouver</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Whitehorse</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Winnipeg</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Yakutat</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">America/Yellowknife</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Casey</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Davis</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/DumontDUrville</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Macquarie</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Mawson</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/McMurdo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Palmer</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Rothera</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Syowa</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Troll</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Antarctica/Vostok</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Arctic/Longyearbyen</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Aden</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Almaty</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Amman</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Anadyr</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Aqtau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Aqtobe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Ashgabat</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Atyrau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Baghdad</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Bahrain</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Baku</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Bangkok</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Barnaul</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Beirut</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Bishkek</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Brunei</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Chita</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Choibalsan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Colombo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Damascus</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Dhaka</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Dili</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Dubai</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Dushanbe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Famagusta</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Gaza</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Hebron</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Ho_Chi_Minh</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Hovd</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Irkutsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Jakarta</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Jayapura</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Jerusalem</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kabul</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kamchatka</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Karachi</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kathmandu</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Khandyga</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kolkata</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Krasnoyarsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kuala_Lumpur</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kuching</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Kuwait</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Macau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Magadan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Makassar</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Manila</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Muscat</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Nicosia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Novokuznetsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Novosibirsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Omsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Oral</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Phnom_Penh</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Pontianak</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Pyongyang</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Qatar</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Qyzylorda</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Riyadh</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Sakhalin</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Samarkand</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Shanghai</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Singapore</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Srednekolymsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Taipei</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Tashkent</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Tbilisi</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Tehran</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Thimphu</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Tokyo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Tomsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Ulaanbaatar</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Urumqi</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Ust-Nera</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Vientiane</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Vladivostok</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Yakutsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Yangon</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Yekaterinburg</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Asia/Yerevan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Azores</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Bermuda</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Canary</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Cape_Verde</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Faroe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Madeira</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Reykjavik</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/South_Georgia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/St_Helena</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Atlantic/Stanley</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Adelaide</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Brisbane</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Broken_Hill</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Currie</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Darwin</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Eucla</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Hobart</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Lindeman</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Lord_Howe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Melbourne</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Perth</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Australia/Sydney</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Amsterdam</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Andorra</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Astrakhan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Athens</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Belgrade</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Berlin</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Bratislava</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Brussels</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Bucharest</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Budapest</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Busingen</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Chisinau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Copenhagen</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Dublin</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Gibraltar</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Guernsey</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Helsinki</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Isle_of_Man</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Istanbul</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Jersey</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Kaliningrad</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Kiev</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Kirov</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Lisbon</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Ljubljana</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/London</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Luxembourg</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Madrid</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Malta</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Mariehamn</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Minsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Monaco</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Moscow</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Oslo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Paris</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Podgorica</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Prague</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Riga</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Rome</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Samara</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/San_Marino</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Sarajevo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Saratov</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Simferopol</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Skopje</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Sofia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Stockholm</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Tallinn</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Tirane</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Ulyanovsk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Uzhgorod</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Vaduz</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Vatican</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Vienna</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Vilnius</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Volgograd</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Zagreb</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Zaporozhye</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Europe/Zurich</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Antananarivo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Chagos</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Christmas</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Cocos</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Comoro</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Kerguelen</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Mahe</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Maldives</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Mauritius</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Mayotte</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Indian/Reunion</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Apia</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Auckland</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Bougainville</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Chatham</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Chuuk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Easter</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Efate</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Enderbury</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Fakaofo</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Fiji</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Funafuti</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Galapagos</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Gambier</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Guadalcanal</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Guam</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Honolulu</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Johnston</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Kiritimati</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Kosrae</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Kwajalein</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Majuro</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Marquesas</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Midway</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Nauru</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Niue</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Norfolk</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Noumea</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Pago_Pago</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Palau</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Pitcairn</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Pohnpei</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Port_Moresby</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Rarotonga</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Saipan</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Tahiti</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Tarawa</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Tongatapu</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Wake</li>
	<li class="mdl-menu__item" e-select-timezone="{{ $name }}">Pacific/Wallis</li>
</ul>
